export const API_END_POINTS = {
  GET_ALL_CHARACTERS: '/character',
  GET_LOCATION_DETAIL: '/location/:ids',
  GET_EPISODE_DETAIL: '/episode/:id'
}

export const API_IDS = {
  GET_ALL_CHARACTERS: 'GET_ALL_CHARACTERS',
  GET_LOCATION_DETAIL: 'GET_LOCATION_DETAIL',
  GET_EPISODE_DETAIL: 'GET_EPISODE_DETAIL'
}