export const icons = {
  EYE_ICON: require('../../images/eyeIcon.png'),
  SIGN_IN: require('../../images/signin.png'),
  BACK_ARROW: require('../../images/backArrow.png'),
  LOGO: require('../../images/logo.png'),
  PERSON: require('../../images/jokePerson.png'),
  BRICK: require('../../images/brick.png'),
  SET_PASSWORD: require('../../images/SetPassword.png'),
  TICK: require('../../images/tick.png'),
  CROSS: require('../../images/wrong.png'),
  HOME: require('../../images/home.png'),
  NUDGES: require('../../images/Nudges.png'),
  PREFERNCES: require('../../images/preferences.png'),
  DISCUSSION: require('../../images/Discussion.png'),
  EVENTS: require('../../images/events.png'),
  ADD_DISCUSSSION: require('../../images/AddDiscussion.png'),
  REFLECTION: require('../../images/reflection.png'),
  THOUGHT_PROCESS: require('../../images/thoughProcess.png'),
  COMMENT: require('../../images/comment.png'),
  RIGHT_ARROW: require('../../images/whiteRightArrow.png')
}