export const icons = {
  SOCIO_HOOD_LOGO: require('../../images/SocioHoodLOGO.png'),
  EYE_ICON: require('../../images/eyeIcon.png'),
  BACK_ARROW: require('../../images/BackArrow.png'),
  FORWARD_ARROW:  require('../../images/ForwardArrow.png'),
  HOME_TAB: require('../../images/Home.png'),
  ACTIVITY_TAB: require('../../images/Activity.png'),
  ADD_MORE_TAB: require('../../images/AddMore.png'),
  STAFF_TAB: require('../../images/Staff.png'),
  CHAT_TAB: require('../../images/Chat.png'),
  HOME_DUMMY_ICON: require('../../images/Dummy.png'),
  PRE_APPROVED_ENTRY: require('../../images/PreApprovedEntry.png'),
  NOTICE_BOARD: require('../../images/NoticeBoard.png'),
  COMPLAIN: require('../../images/Complain.png'),
  INFO_SYMBOL: require('../../images/Info.png'),
  INFO_CIRCLE: require('../../images/InfoCircle.png'),
  PERSON: require('../../images/Person.png'),
  VENDOR: require('../../images/Vendor.png'),
  BACK_CARET: require('../../images/BackCaret.png'),
  TENANT: require('../../images/TenantIcon.png'),
  OWNER: require('../../images/OwnerIcon.png'),
  DEFAULT_PROFILE: require('../../images/DefaultProfile.png'),
  OTP_VERIFICATION: require('../../images/OtpVerification.png'),
  VERIFY_EMAIL: require('../../images/EmailVerify.png'),
  SOCIETY: require('../../images/SearchSociety.png'),
  APPROVAL_PENDING: require('../../images/ApprovalPending.png'),
  LOGOUT: require('../../images/Logout.png')
}